### ISSUE TITLE
Running a program with `--help`/`-h` option  should not result in an exit-code other than 0

### ISSUE THREAD

**Issue by a4z** [DavidGamba/go-getoptions#9]
When asking for command line arguments help, the program exits with an exit-code other than 0 , most likely always 1. 

I think this is not correct, since the program did exactly what was asked for.

Example from my toy program
```
-> go run . --help
NAME:
    cmdargs - A toy program to lear go command line processing

SYNOPSIS:
    cmdargs [--help|-h|-?] <command> [<args>]

COMMANDS:
    command1    This is the first command
    command2    This is the second command
    command3    The third command
    help        Use 'cmdargs help <command>' for extra details.

OPTIONS:
    --help|-h|-?    (default: false)

Use 'cmdargs help <command>' for extra details.
exit status 1


-> go run . command3  --help
NAME:
    cmdargs command3 - The third command

SYNOPSIS:
    cmdargs command3 [--help|-h|-?] <command> [<args>]

COMMANDS:
    sub-cmd    

OPTIONS:
    --help|-h|-?    (default: false)

Use 'cmdargs command3 help <command>' for extra details.
exit status 1

-> echo $?
1
```

but programs should always return 0 when executed with some help option, see for example

```
-> go help
...
-> echo $?
0
```
or any other tool with `--help`/`-h` options

```
-> xcode-select --help
Usage: xcode-select [options]

Print or change the path to the active developer directory. This directory
controls which tools are used for the Xcode command line tools (for example,
xcodebuild) as well as the BSD development commands (such as cc and make).

Options:
  -h, --help                  print this help message and exit
  -p, --print-path            print the path of the active developer directory
  -s <path>, --switch <path>  set the path for the active developer directory
  --install                   open a dialog for installation of the command line developer tools
  -v, --version               print the xcode-select version
  -r, --reset                 reset to the default command line tools path

-> echo $?
0
```

It would be nice if go-getoptions would behave per default likewise it is expected to behave when the  `--help`/`-h`  is processed, and only produces other exitcodes than 0 when the help is shown due to unknown arguments

**Comment by DavidGamba** [comment]
I personally consider that calling the help should exit with 1 so it is not done by mistake in a calling application.

The only times you should call help is interactively as a user in which case the exit code of 1 is not a problem. It is problem if you are trying to parse the output of the help in some way. In which case the exit of 1 will probably interrupt your application flow.

I prefer to have options that print any info you would want to parse out of the help (like if you are adding the version on the help).
Also, since the autocompletion is built in, there is no need for that either.

That said, the goal of the tool is to be flexible and it shouldn't have the exit code hardcoded without a way to override it.

The next version will properly handle the following construct:

```
	err = opt.Dispatch(ctx, remaining)
	if err != nil {
		if errors.Is(err, getoptions.ErrorHelpCalled) {
			return 0
		}
		fmt.Fprintf(os.Stderr, "ERROR: %s\n", err)
		return 1
	}
```

So you can decide how to exit your help yourself.

**Comment by a4z** [comment]
> So you can decide how to exit your help yourself.

That sounds like a great solution!

**Comment by DavidGamba** [comment]
@a4z this is adressed in the next release: https://github.com/DavidGamba/go-getoptions/releases/tag/v0.25.0-alpha.1

I labelled it as alpha because I want to run it in prod for a while though as usual it has 100% test coverage.

Please test it out when you have a chance and let me know.
I added an example that is fairly comprehensive: https://github.com/DavidGamba/go-getoptions/tree/master/examples/complex

**Comment by a4z** [comment]
Awesome! 
I played now with the examples you provide, and they allow that help return value customisation.
So I think we can close that issue since I am confident I can transfer the required adoptions for 0.25.0 into my code. 

The new examples are also much more clear to me how to add subcommands, that's great.
Thanks a lot!

**Comment by DavidGamba** [comment]
@a4z I also recorded a video: https://youtu.be/1ZGyIkC5shM
